redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\jalme\\Desktop\\dash1\\guardline\\frontend"
publishOrigin = "config"
commandOrigin = "config"
base = "C:\\Users\\jalme\\Desktop\\dash1\\guardline\\frontend"
command = "echo 'Static dashboard — no build'"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/"
to = "/guardline.html"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]